server:
  port: 9092
myyml:
  string: hello,yml!

# 连接数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8mb4&useSSL=true
    name: root
    password: 12345678

mystring: 你好\n世界
mystring2: '你好\n世界'
mystring3: "你好\\n世界"

# 对象写法 1
student:
  id: 1
  name: 张三
  age: 18

# 对象写法 2
student2: { id: 2,name: 李四,age: 20 }

# 集合
dbtypes: { name: [ mysql,sqlserver,db2 ] }