# 生产环境的配置文件

# 配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mycnblog?characterEncoding=utf8
    username: root
    password: daxiangzi
    driver-class-name: com.mysql.cj.jdbc.Driver