# 配置数据库的连接字符串
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mycnblog?characterEncoding=utf8
    username: root
    password: daxiangzi
    driver-class-name: com.mysql.cj.jdbc.Driver

# 设置 Mybatis 的 xml 保存路径
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  # 配置打印 MyBatis 执行的 SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置日志级别
logging:
  level:
    com:
      example:
        springtransaction: debug